server:
  port: 8801
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nssc?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

--- # mybatis plus 相关配置
mybatis-plus:
  # 对应的 XML 文件位置
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: nssc.bc.**.entity
  configuration:
    # 自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
    # MyBatis 自动映射策略
    # NONE：不启用 | PARTIAL：只对非嵌套 | resultMap 自动映射 | FULL：对所有 | resultMap 自动映射
    auto-mapping-behavior: partial
    # MyBatis 自动映射时未知列或未知属性处理策
    # NONE：不做处理 WARNING：打印相关警告 FAILING：抛出异常和详细信息
    autoMappingUnknownColumnBehavior: NONE
    # 日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 是否打印 Logo banner
    banner: true
    db-config:
      # 主键类型: AUTO 自增 | NONE 空  | INPUT 用户输入 | ASSIGN_ID 雪花 | ASSIGN_UUID 唯一UUID
      idType: AUTO
      # 全局逻辑删除的实体字段名
      logic-delete-field: delFlag
      # 逻辑未删除值
      logicNotDeleteValue: 0
      # 逻辑已删除值
      logicDeleteValue: 1
      # 在 insert 的时候的字段验证策略: IGNORED 忽略 | NOT_NULL 非NULL | NOT_EMPTY 非空 | DEFAULT 默认 | NEVER 不加入 SQL
      insertStrategy: NOT_NULL
      # 在 update 的时候的字段验证策略
      updateStrategy: NOT_NULL
      # 在 select 的时候的字段验证策略，既 wrapper 根据内部 entity 生成的 where 条件
      where-strategy: NOT_NULL